# Generated by Django 4.2.7 on 2024-08-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_post_count_views_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Дата изменения'),
        ),
    ]
