# Generated by Django 4.2.7 on 2024-08-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, default='Информация обо мне будет позже ... ', null=True, verbose_name='О себе'),
        ),
    ]
