# Generated by Django 4.2.7 on 2024-08-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(blank=True, default='Работа будет добавлена позже', max_length=100, null=True, verbose_name='Работа'),
        ),
    ]
